Update docs
lifinance/contracts pull request #202
Opened 2023-02-17 08:22 UTC by ezynda3

2023-02-17 09:16 UTC, maxklenk reviewed
Nice, that helps. Just added two small comments.

2023-02-17 09:16 UTC, maxklenk commented on docs/Deploy.md
> +
Perhaps add that the CREATE3_FACTORY has to be deployed to that chain first using the other repository.

2023-02-17 10:46 UTC, satoshi-lifi commented on docs/Deploy.md
> +If you want to deploy an immutable diamond, please skip to this section
maybe the link to the section is missed?

2023-02-17 10:50 UTC, satoshi-lifi approved these changes
LGTM

2023-02-18 15:23 UTC, maxklenk requested changes
When testing a deployment based on the configs I found some more points.

2023-02-20 07:03 UTC, ezynda3 commented on .env.example
> +#ETHERSCAN
Verification doesn't work there yet

2023-02-20 09:52 UTC, maxklenk approved these changes

2023-02-20 10:41 UTC, merged