feat: improve gas consumption for CBridgeFacetPacked
lifinance/contracts pull request #326
Opened 2023-04-20 12:54 UTC by ezynda3

2023-04-21 12:04 UTC, maxklenk requested changes
Great. Tests for the decoders would be good to add.

2023-04-21 12:04 UTC, maxklenk commented on src/Facets/CBridgeFacetPacked.sol
> +            _data.length >= 40,
Why 40? we are reading up to 60 below.

2023-04-21 12:04 UTC, maxklenk commented on src/Facets/CBridgeFacetPacked.sol
> +        require(_data.length >= 76, "data passed is not the correct length");
76 looks too long

2023-04-21 14:14 UTC, merged

2023-04-24 03:03 UTC, 0xDEnYO commented on test/solidity/Facets/HopFacetPackedL1.t.sol
> +    // Encode
Why is this all commented out?
Can it be removed?

2023-04-24 03:03 UTC, 0xDEnYO commented on test/solidity/Facets/HopFacetPackedL2.t.sol
> +
All of my comments on test/solidity/Facets/HopFacetPackedL1.t.sol seem to apply here, too

2023-04-24 03:03 UTC, 0xDEnYO commented on test/solidity/Gas/CBridgeFacetPackedARB.gas.t.sol
>          /// Perpare CBridgeFacetPacked
typo

2023-04-24 03:03 UTC, 0xDEnYO commented on test/solidity/Gas/CBridgeFacetPackedARB.gas.t.sol
> +    function testStartBridgeTokensViaCBridgeERC20Packed_StandAlone() public {
My comment about checking events in test cases also applies here