Update fee collectors ServiceFeeCollector v1.0.1, LiFuelFeeCollector v1.0.1, LIFuelFacet v1.0.1
lifinance/contracts pull request #585
Opened 2024-01-25 11:18 UTC by ezynda3

2024-01-31 06:51 UTC, 0xDEnYO commented on src/Periphery/LiFuelFeeCollector.sol
> +/// @custom:version 1.0.1
need to update PR title, too, please

2024-01-31 06:51 UTC, 0xDEnYO commented on src/Periphery/ServiceFeeCollector.sol
> +/// @custom:version 1.0.1
same as above

2024-01-31 06:52 UTC, 0xDEnYO commented on test/solidity/Periphery/ServiceFeeCollector.t.sol
> +        feeCollector.collectNativeGasFees{ value: fee }(
I think it could be nice to have a test case that tests the behaviour we just had issues with to ensure that things work as intended

2024-01-31 09:37 UTC, maxklenk requested changes

2024-01-31 09:37 UTC, maxklenk commented on src/Periphery/LiFuelFeeCollector.sol
> +        msg.sender.call{ value: msg.value - feeAmount }("");
Add check to validate if there is a amount to send back. e.g. the lifuel bridge sends the exact amount needed.

2024-01-31 09:37 UTC, maxklenk commented on src/Periphery/ServiceFeeCollector.sol
> +        msg.sender.call{ value: msg.value - feeAmount }("");
Also check here

2024-02-01 08:00 UTC, maxklenk requested changes
Please update the `LIFuelFacet.sol` The version should be increased and the linked Fee collector has to be updated as we have a dedicated lifuel fee collector.
Update line 20
`string internal constant FEE_COLLECTOR_NAME = "ServiceFeeCollector";`

2024-02-01 08:00 UTC, maxklenk commented on src/Periphery/ServiceFeeCollector.sol
>          );
Why do we need that function still? We collect gas fees in the LiFuelFeeCollector.
Also the event emits `msg.value` instead of the `feeAmount`.

2024-02-05 11:37 UTC, maxklenk approved these changes
Nice, that looks like what I expected.

2024-02-06 09:38 UTC, merged