Update ZKSync Scripts
lifinance/contracts pull request #835
Opened 2024-10-16 09:26 UTC by ezynda3

# Which Jira task belongs to this PR?

# Why did I implement it this way?

# Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] This pull request is as small as possible and only tackles one problem
- [ ] I have added tests that cover the functionality / test the bug
- [ ] I have updated any required documentation

# Checklist for reviewer (DO NOT DEPLOY and contracts BEFORE CHECKING THIS!!!)

- [ ] I have checked that any arbitrary calls to external contracts are validated and or restricted
- [ ] I have checked that any privileged calls (i.e. storage modifications) are validated and or restricted
- [ ] I have ensured that any new contracts have had AT A MINIMUM 1 preliminary audit conducted on <date> by <company/auditor>

2024-10-25 04:49 UTC, 0xDEnYO commented on archive/src/DeBridgeDlnFacet.sol
guess it's not desired that this PR reinstates this facet, right?

2024-10-25 06:04 UTC, 0xDEnYO requested changes

2024-10-25 06:04 UTC, 0xDEnYO commented on script/helperFunctions.sh
> +    --verifier  --zksyncsourcify
is this correct (also for non-zksync cases)?

2024-10-25 06:04 UTC, 0xDEnYO commented on script/deploy/zksync/utils/UpdateScriptBase.sol
> +        address refundWallet = json.readAddress(".deployerWallet");
variable name does not match with code (refundWallet vs. deployerWallet)

2024-10-25 07:26 UTC, ezynda3 commented on script/scriptMaster.sh
> +    # Handle ZkSync
This will most likely fail. Will need to address it in a different PR.

2024-10-25 08:38 UTC, 0xDEnYO submitted a review, later dismissed

2024-10-25 08:39 UTC, 0xDEnYO submitted a review, later dismissed

2024-10-28 07:01 UTC, merged

2024-10-30 09:11 UTC, ezynda3 commented
Only pragmas were updated in this PR and no actual business logic was updated so AuditRequired was removed.