Integrate WithdrawablePeriphery [ERC20Proxy v1.1.0,Executor v2.1.0,LiFiDEXAggregator v1.6.0,Receiver v2.1.0,ReceiverAcrossV3 v1.1.0,ReceiverStargateV2 v1.1.0,RelayerCelerIM v2.1.1,TokenWrapper v1.1.0]
lifinance/contracts pull request #909
Opened 2024-12-19 10:19 UTC by ezynda3

# Which Jira task belongs to this PR?

# Why did I implement it this way?

# Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] This pull request is as small as possible and only tackles one problem
- [x] I have added tests that cover the functionality / test the bug
- [ ] For new facets: I have checked all points from this list: https://www.notion.so/lifi/New-Facet-Contract-Checklist-157f0ff14ac78095a2b8f999d655622e
- [ ] I have updated any required documentation

# Checklist for reviewer (DO NOT DEPLOY and contracts BEFORE CHECKING THIS!!!)

- [ ] I have checked that any arbitrary calls to external contracts are validated and or restricted
- [ ] I have checked that any privileged calls (i.e. storage modifications) are validated and or restricted
- [ ] I have ensured that any new contracts have had AT A MINIMUM 1 preliminary audit conducted on <date> by <company/auditor>

2025-01-03 17:09 UTC, sujithsomraaj commented on src/Periphery/ReceiverAcrossV3.sol
>          owner = _owner;
@ezynda3 is this setter necessary ?

2025-01-04 12:33 UTC, maxklenk commented on src/Periphery/ReceiverAcrossV3.sol
>          owner = _owner;
But the `owner = _owner;` is handled in there as well, so it should not be necessary here.

2025-01-06 09:07 UTC, maxklenk requested changes

2025-01-06 09:07 UTC, maxklenk commented on src/Periphery/TokenWrapper.sol
> +    ) WithdrawablePeriphery(_owner) {
I think this comment is legit, we need to adjust the deploy scripts.

2025-01-07 09:24 UTC, ezynda3 commented on src/Periphery/TokenWrapper.sol
> +    ) WithdrawablePeriphery(_owner) {
fixed

2025-01-07 09:27 UTC, ezynda3 commented on src/Periphery/ReceiverAcrossV3.sol
>          owner = _owner;
I will remove `owner = _owner;` to stay consistent with the rest of the codebase.

2025-01-07 09:29 UTC, ezynda3 commented on src/Periphery/ReceiverAcrossV3.sol
>          owner = _owner;
Fixed

2025-01-07 15:11 UTC, maxklenk submitted a review, later dismissed

2025-01-09 04:33 UTC, ezynda3 commented on script/deploy/zksync/DeployTokenWrapper.s.sol
> +        );
not needed

2025-01-09 04:34 UTC, ezynda3 commented on script/deploy/facets/DeployTokenWrapper.s.sol
> +        );
not needed

2025-01-09 17:57 UTC, louisbrown0212 commented on src/Periphery/RelayerCelerIM.sol
> +            emit TokensWithdrawn(_assetAddress, sendTo, _amount);
```suggestion
            address payable sendTo = payable(
                (LibUtil.isZeroAddress(_to)) ? msg.sender : _to
            );
            LibAsset.transferAsset(_assetAddress, sendTo, _amount);
            emit TokensWithdrawn(_assetAddress, sendTo, _amount);
```

2025-01-10 00:38 UTC, louisbrown0212 commented
In `ReceiverAcrossV3Test`, the names of functions for `withdrawToken` are not updated. They still says `PullToken`.
The descriptions for `pullToken` are not removed from `Receiver.md`, `ReceiverAcrossV3.md`, and `ReceiverStargateV2.md`

2025-01-10 05:14 UTC, ezynda3 commented on audit/auditLog.json
> +      "auditCommitHash": "fb4c7a4e02c5fd214d78b8cdc5d4a03fa0b06ab9"
fixed

2025-01-10 05:15 UTC, ezynda3 commented on src/Periphery/RelayerCelerIM.sol
> +            emit TokensWithdrawn(_assetAddress, sendTo, _amount);
fixed

2025-01-10 13:45 UTC, maxklenk submitted a review, later dismissed
good, when to open comment is fixed.

2025-01-10 15:41 UTC, ezynda3 commented on src/Periphery/LiFiDEXAggregator.sol
>  import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";
fixed

2025-01-10 16:01 UTC, maxklenk approved these changes

2025-01-10 16:06 UTC, merged