Include outputAmountPercent for origin swaps to help improve price
lifinance/contracts pull request #911
Opened 2024-12-31 04:03 UTC by ezynda3

# Which Jira task belongs to this PR?

# Why did I implement it this way?

# Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] This pull request is as small as possible and only tackles one problem
- [ ] I have added tests that cover the functionality / test the bug
- [ ] For new facets: I have checked all points from this list: https://www.notion.so/lifi/New-Facet-Contract-Checklist-157f0ff14ac78095a2b8f999d655622e
- [ ] I have updated any required documentation

# Checklist for reviewer (DO NOT DEPLOY and contracts BEFORE CHECKING THIS!!!)

- [ ] I have checked that any arbitrary calls to external contracts are validated and or restricted
- [ ] I have checked that any privileged calls (i.e. storage modifications) are validated and or restricted
- [ ] I have ensured that any new contracts have had AT A MINIMUM 1 preliminary audit conducted on <date> by <company/auditor>

2025-01-03 11:24 UTC, maxklenk requested changes

2025-01-03 11:24 UTC, maxklenk commented on test/solidity/Facets/AcrossFacetPackedV3.t.sol
> +            outputAmountPercent: 10000, // 10000 = 100.00%
This amount is different to other examples

2025-01-03 11:24 UTC, maxklenk commented on test/solidity/Facets/AcrossFacetV3.t.sol
> +
We should also add an check for the `V3FundsDeposited` event exposed by across to verify that the calculated amount matches our expectations.

2025-01-03 11:24 UTC, maxklenk commented on test/solidity/Facets/CalldataVerificationFacet.t.sol
> +                outputAmountPercent: 10000, // 10000 = 100.00%
Wrong value

2025-01-06 06:15 UTC, ezynda3 commented on src/Facets/AcrossFacetV3.sol
> +    /// @param outputAmountPercent The percentage of the output amount with 18 decimal precision (0.7550e18 = 75.50%, 0.99e18 = 99.00%)
I think this is fixed

2025-01-06 09:29 UTC, merged